export const COLOURS = {
    white: '#ffffff',
    black: '#000000',
    lightGray: '#B3B4B6',
    accent: '#ac8d4e',
    accentRed: '#b83d0f',
    accentPink: '#F96165',
  };
  
  export const Categories = [
    {
      name: 'จานด่วน',
      image: require('../database/images/จานด่วน/กะเพรา.jpg'),
      items: [
        {
          name: 'ข้าวกะเพราหมูสับไข่ดาว',
          title: 'อาหารจานเดียวทำง่ายๆ',
          rating: '5.0',
          isTopOfTheWeek: true,
          image: require('../database/images/จานด่วน/กะเพรา.jpg'),
          Type: 'ผัด',
          Skill: 'ง่าย',
          Time: 15,
          material: '- หมูสับ 300 กรัม \n- ใบกะเพรา 50 กรัม \n- พริกแดงจินดา 1 ช้อนโต๊ะ \n- กระเทียม 1 ช้อนโต๊ะ \n- ซอสหอยนางรม 1 ช้อนโต๊ะ \n- น้ำปลา 1 ช้อนโต๊ะ \n- น้ำตาลทราย 1 ช้อนชา \n- น้ำมัน (สำหรับผัดกะเพรา) 1 ช้อนโต๊ะ \n- ไข่ไก่ 1 ฟอง \n- น้ำมัน (สำหรับทอดไข่ดาว) ½ ถ้วยตวง',
          ingredients: [
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/หมูสับ.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/ใบกระเพรา.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/จินดาแดง.png'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/กระเทียม.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/ซอสหอย.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/น้ำปลา.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/น้ำตาล.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/น้ำมัน.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/ไข่ไก่.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/น้ำมันปาล์ม.jpg'),
          ],
          FoodList: 'STEP 1 : ทอดไข่ดาวกรอบ ๆ\n- ตั้งกระใส่น้ำมันรอให้ร้อนจัด ค่อยตอกไข่ไก่ลงไปทอดจนไข่ดาวกรอบ ตักขึ้นพักไว้ให้สะเด็ดน้ำมัน\n \nSTEP 2 : ทำผัดกะเพราหมูสับ\n- ตั้งกระทะใส่น้ำมันให้พอร้อน แล้วใส่กระเทียม และพริกแดงจินดาลงไปผัดจนส่งกลิ่นหอม จากนั้นใส่หมูสับลงไปผัด\n \n- เมื่อหมูเริ่มสุกให้ปรุงรสด้วย ซอสหอยนางรม น้ำปลา และน้ำตาลทราย ผัดจนทุกอย่างเข้ากันดี จากนั้นใส่ใบกะเพราลงไปผัดให้สลดลงเล็กน้อย\n \nSTEP 3 : จัดเสิร์ฟผัดกะเพราหมูสับไข่ดาว \n- ตักข้าวสวยร้อน ๆ ใส่จานราดด้วยหมูสับผัดกะเพราหมูสับ โปะด้วยไข่ดาวกรอบ ๆ เสิร์ฟพร้อมน้ำปลาพริก เพียงเท่านี้เราก็จะได้เมนูผัดกะเพราเด็ด ๆ ที่ทำกินเองได้แล้ว!'
        },
        {
          name: 'ผัดไทยใส่ไข่',
          title: 'เครื่องน้อย เน้นเส้น สำหรับจานด่วน',
          rating: '4.5',
          isTopOfTheWeek: false,
          image: require('../database/images/จานด่วน/ผัดไทย.jpg'),
          Type: 'ผัด',
          Skill: 'ปานกลาง',
          Time: 30,
          material: '- กุ้งแห้ง 1 ช้อนโต๊ะ \n- ไชโป๊ 1 ช้อนโต๊ะ \n- หอมแดงสับหยาบ 2 ช้อนโต๊ะ \n- กระเทียมสับ 2 ช้อนโต๊ะ \n- น้ำมันพืช 2 ช้อนโต๊ะ \n- เต้าหู้แข็งหั่นแท่ง 3 ช้อนโต๊ะ \n- เส้นผัดไทยแช่น้ำ 150 กรัม \n- ใบกุ้ยช่าย 30 กรัม \n- ไข่เป็ด 2 ฟอง \n- ถั่วลิสงป่น 2 ช้อนโต๊ะ \n- พริกป่น (ตามชอบ) \n- น้ำตาลมะพร้าว 200 กรัม \n- น้ำปลา 200 มิลลิลิตร \n- น้ำมะขามเปียก 200 มิลลิลิตร',
          ingredients: [
            require('../database/images/จานด่วน/ส่วนผสม_ผัดไทย/กุ้งแห้ง.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_ผัดไทย/ไชโป๊.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_ผัดไทย/หอมแดง.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_ผัดไทย/กระเทียม.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_ผัดไทย/น้ำมัน.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_ผัดไทย/เต้าหู้.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_ผัดไทย/เส้นผัดไทย.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_ผัดไทย/กุยช่าย.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_ผัดไทย/ไข่เป็ด.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_ผัดไทย/ถั่ว.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_ผัดไทย/พริกป่น.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_ผัดไทย/น้ำตาลมะพร้าว.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_ผัดไทย/น้ำปลา.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_ผัดไทย/มะขาม.jpg'),
          ],
          FoodList: 'STEP 1 : เริ่มด้วยการทำน้ำผัดไทยก่อน โดยนำน้ำตาลมะพร้าว น้ำมะขามเปียก และน้ำปลา ใส่ลงในกระทะ เคี่ยวด้วยไฟอ่อน จนส่วนผสมทั้งหมดส่งกลิ่นหอมละลายเป็นเนื้อเดียวกัน ปิดไฟและพักไว้\n \nSTEP 2 : ตั้งกระทะใส่น้ำมัน รอจนน้ำมันเริ่มร้อนใส่หอมแดง กระเทียม และไชโป๊ลงไป ผัดจนส่งกลิ่นหอม จึงใส่เต้าหู้แข็งลงไปผัดต่ออีกสักครู่พอสุก\n \nSTEP 3 : จากนั้นใช้ไฟแรง ใส่เส้นผัดไทยลงไป ผัดให้เส้นอ่อนสุกนุ่ม แล้วจึงราดด้วยน้ำซอสมะขามที่เตรียมไว้ประมาณ 2 ทัพพี\n \nSTEP 4 : เมื่อน้ำผัดไทยซึมเข้าเส้นแล้ว ให้ใส่ถั่วงอก และใบกุ้ยช่าย ตามด้วยตอกไข่เป็ดใส่ลงไป โดยไข่เป็ดให้ขยี้จนไข่แตก พอไข่เริ่มสุกจึงผัดคลุกเคล้าให้ส่วนผสมทั้งหมดเข้ากัน\n \nSTEP 5 : ปิดไฟตักใส่จาน โรยด้วยถั่วป่น และพริกป่น ปริมาณตามชอบ กินกับถั่วงอกดิบและกุ้ยช่ายสด ยิ่งเพิ่มความอร่อยกลมกล่อมมากขึ้น '
        },
        {
          name: 'ข้าวผัดโบราณ ',
          title: 'เมนูยอดนิยม รับประทานง่าย',
          rating: '4.2',
          isTopOfTheWeek: false,
          image: require('../database/images/จานด่วน/ข้าวผัด.jpg'),
          Type: 'ผัด',
          Skill: 'ง่าย',
          Time: 15,
        },
      ],
    },
    {
      name: 'อาหารอีสาน',
      image: require('../database/images/อาหารอีสาน/ส้มตำ.jpg'),
      items: [
        {
          name: 'ส้มตำปูปลาร้า',
          title: 'อร่อย แซ่บนัว',
          rating: '5.0',
          isTopOfTheWeek: true,
          image: require('../database/images/อาหารอีสาน/ส้มตำ.jpg'),
          Type: 'ตำ',
          Skill: 'ง่าย',
          Time: 15,
        },
        {
          name: 'ลาบหมู',
          title: 'อร่อย หอมข้าวคั่ว',
          rating: '4.5',
          isTopOfTheWeek: false,
          image: require('../database/images/อาหารอีสาน/ลาบหมู.jpg'),
          Type: 'ลวก',
          Skill: 'ปานกลาง',
          Time: 20,
        },
        {
          name: 'คอหมูย่าง',
          title: 'จิ้มแจ่ว แซ่บนัว',
          rating: '4.2',
          isTopOfTheWeek: false,
          image: require('../database/images/อาหารอีสาน/คอหมูย่าง.jpg'),
          Type: 'ย่าง',
          Skill: 'ยาก',
          Time: 35,
        },
      ],
    },
    {
      name: 'อาหารใต้',
      image: require('../database/images/อาหารใต้/ผัดสะตอกุ้ง.jpg'),
      items: [
        {
          name: 'ผัดสะตอกุ้ง',
          title: 'หรอยแรง!',
          rating: '5.0',
          isTopOfTheWeek: true,
          image: require('../database/images/อาหารใต้/ผัดสะตอกุ้ง.jpg'),
          Type: 'ผัด',
          Skill: 'ปานกลาง',
          Time: 25,
        },
        {
          name: 'คั่วกลิ้ง',
          title: 'ทานกับข้าวสวยร้อนๆ อร่อยมาก',
          rating: '4.5',
          isTopOfTheWeek: false,
          image: require('../database/images/อาหารใต้/คั่วกลิ้ง.jpg'),
          Type: 'ผัด',
          Skill: 'ง่าย',
          Time: 20,
        },
        {
          name: 'แกงไตปลา',
          title: 'หรอยแรง!',
          rating: '4.2',
          isTopOfTheWeek: false,
          image: require('../database/images/อาหารใต้/แกงไตปลา.png'),
          Type: 'ต้ม',
          Skill: 'ยาก',
          Time: 30,
        },
      ],
    },
    {
      name: 'อาหารเหนือ',
      image: require('../database/images/อาหารเหนือ/น้ำพริกหนุ่ม.jpg'),
      items: [
        {
          name: 'น้ำพริกหนุ่ม',
          title: 'ทำเองง่ายๆ ลำแต๊ๆเจ๊า',
          rating: '5.0',
          isTopOfTheWeek: true,
          image: require('../database/images/อาหารเหนือ/น้ำพริกหนุ่ม.jpg'),
          Type: 'น้ำพริก',
          Skill: 'ง่าย',
          Time: 30,
        },
        {
          name: 'ข้าวซอยไก่',
          title: 'หอมแกง อร่อยมาก',
          rating: '4.5',
          isTopOfTheWeek: false,
          image: require('../database/images/อาหารเหนือ/ข้าวซอยไก่.jpg'),
          Type: 'บะหมี่',
          Skill: 'ปานกลาง',
          Time: 50,
        },
        {
          name: 'แกงฮังเล',
          title: 'หอมเครื่องแกง รสชาติเข้มข้น',
          rating: '4.2',
          isTopOfTheWeek: false,
          image: require('../database/images/อาหารเหนือ/แกงฮังเล.jpg'),
          Type: 'แกง',
          Skill: 'ยาก',
          Time: 60,
        },
      ],
    },
    {
      name: 'ไข่',
      image: require('../database/images/ไข่/ไข่เจียว.jpg'),
      items: [
        {
          name: 'ไข่เจียวหมูสับ',
          title: 'เหลืองทอง หอมกรุ่น',
          rating: '5.0',
          isTopOfTheWeek: true,
          image: require('../database/images/ไข่/ไข่เจียว.jpg'),
          Type: 'ทอด',
          Skill: 'ง่าย',
          Time: 15,
        },
        {
          name: 'ผัดวุ้นเส้นไข่',
          title: 'อร่อยได้ง่ายๆ',
          rating: '4.5',
          isTopOfTheWeek: false,
          image: require('../database/images/ไข่/ผัดวุ้นเส้น.jpg'),
          Type: 'ผัด',
          Skill: 'ง่าย',
          Time: 15,
        },
        {
          name: 'ไข่พะโล้ + น่องไก่',
          title: 'รสชาติเข้มข้น กลมกล่อม',
          rating: '4.2',
          isTopOfTheWeek: false,
          image: require('../database/images/ไข่/ไข่พะโล้.jpg'),
          Type: 'ต้ม',
          Skill: 'ยาก',
          Time: 60,
        },
      ],
    },
    {
      name: 'ขนม',
      image: require('../database/images/ขนม/ข้าวเหนียวมะม่วง.jpg'),
      items: [
        {
          name: 'ข้าวเหนียวมะม่วง',
          title: 'หอมหวานมันกะทิ',
          rating: '5.0',
          isTopOfTheWeek: true,
          image: require('../database/images/ขนม/ข้าวเหนียวมะม่วง.jpg'),
          Type: 'ผลไม้ขนมหวาน',
          Skill: 'ปานกลาง',
          Time: 50,
        },
        {
          name: 'บัวลอยไข่หวาน',
          title: 'หอมหวานกะทิ อร่อย',
          rating: '4.5',
          isTopOfTheWeek: false,
          image: require('../database/images/ขนม/บัวลอยไข่หวาน.jpg'),
          Type: 'ขนมหวาน',
          Skill: 'ปานกลาง',
          Time: 30,
        },
        {
          name: 'ขนมชั้นใบเตย',
          title: 'หอมกลิ่นใบเตย อร่อยหวานมัน',
          rating: '4.2',
          isTopOfTheWeek: false,
          image: require('../database/images/ขนม/ขนมชั้นใบเตย.jpg'),
          Type: 'ขนมหวาน',
          Skill: 'ยาก',
          Time: 60,
        },
      ],
    },
  ];