export const COLOURS = {
    white: '#ffffff',
    black: '#000000',
    lightGray: '#B3B4B6',
    accent: '#ac8d4e',
    accentRed: '#b83d0f',
    accentPink: '#F96165',
  };
  
  export const Categories = [
    {
      name: 'จานด่วน',
      image: require('../database/images/จานด่วน/กะเพรา.jpg'),
      items: [
        {
          name: 'ข้าวกะเพราหมูสับไข่ดาว',
          title: 'อาหารจานเดียวทำง่ายๆ',
          rating: '5.0',
          isTopOfTheWeek: true,
          image: require('../database/images/จานด่วน/กะเพรา.jpg'),
          Type: 'ผัด',
          Skill: 'ง่าย',
          Time: 15,
          material: '- หมูสับ 300 กรัม \n- ใบกะเพรา 50 กรัม \n- พริกแดงจินดา 1 ช้อนโต๊ะ \n- กระเทียม 1 ช้อนโต๊ะ \n- ซอสหอยนางรม 1 ช้อนโต๊ะ \n- น้ำปลา 1 ช้อนโต๊ะ \n- น้ำตาลทราย 1 ช้อนชา \n- น้ำมัน (สำหรับผัดกะเพรา) 1 ช้อนโต๊ะ \n- ไข่ไก่ 1 ฟอง \n- น้ำมัน (สำหรับทอดไข่ดาว) ½ ถ้วยตวง',
          ingredients: [
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/หมูสับ.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/ใบกระเพรา.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/จินดาแดง.png'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/กระเทียม.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/ซอสหอย.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/น้ำปลา.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/น้ำตาล.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/น้ำมัน.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/ไข่ไก่.jpg'),
            require('../database/images/จานด่วน/ส่วนผสม_กะเพรา/น้ำมันปาล์ม.jpg'),
          ],
          FoodList: 'STEP 1 : ทอดไข่ดาวกรอบ ๆ \nSTEP 2 : ทำผัดกะเพราหมูสับ \nSTEP 3 : จัดเสิร์ฟผัดกะเพราหมูสับไข่ดาว'
        },
        {
          name: 'ผัดไทยใส่ไข่',
          title: 'เครื่องน้อย เน้นเส้น สำหรับจานด่วน',
          rating: '4.5',
          isTopOfTheWeek: false,
          image: require('../database/images/จานด่วน/ผัดไทย.jpg'),
          Type: 'ผัด',
          Skill: 'ปานกลาง',
          Time: 30,
        },
        {
          name: 'ข้าวผัดโบราณ ',
          title: 'เมนูยอดนิยม รับประทานง่าย',
          rating: '4.2',
          isTopOfTheWeek: false,
          image: require('../database/images/จานด่วน/ข้าวผัด.jpg'),
          Type: 'ผัด',
          Skill: 'ง่าย',
          Time: 15,
        },
      ],
    },
    {
      name: 'อาหารอีสาน',
      image: require('../database/images/อาหารอีสาน/ส้มตำ.jpg'),
      items: [
        {
          name: 'ส้มตำปูปลาร้า',
          title: 'อร่อย แซ่บนัว',
          rating: '5.0',
          isTopOfTheWeek: true,
          image: require('../database/images/อาหารอีสาน/ส้มตำ.jpg'),
          Type: 'ตำ',
          Skill: 'ง่าย',
          Time: 15,
        },
        {
          name: 'ลาบหมู',
          title: 'อร่อย หอมข้าวคั่ว',
          rating: '4.5',
          isTopOfTheWeek: false,
          image: require('../database/images/อาหารอีสาน/ลาบหมู.jpg'),
          Type: 'ลวก',
          Skill: 'ปานกลาง',
          Time: 20,
        },
        {
          name: 'คอหมูย่าง',
          title: 'จิ้มแจ่ว แซ่บนัว',
          rating: '4.2',
          isTopOfTheWeek: false,
          image: require('../database/images/อาหารอีสาน/คอหมูย่าง.jpg'),
          Type: 'ย่าง',
          Skill: 'ยาก',
          Time: 35,
        },
      ],
    },
    {
      name: 'อาหารใต้',
      image: require('../database/images/อาหารใต้/ผัดสะตอกุ้ง.jpg'),
      items: [
        {
          name: 'ผัดสะตอกุ้ง',
          title: 'หรอยแรง!',
          rating: '5.0',
          isTopOfTheWeek: true,
          image: require('../database/images/อาหารใต้/ผัดสะตอกุ้ง.jpg'),
          Type: 'ผัด',
          Skill: 'ปานกลาง',
          Time: 25,
        },
        {
          name: 'คั่วกลิ้ง',
          title: 'ทานกับข้าวสวยร้อนๆ อร่อยมาก',
          rating: '4.5',
          isTopOfTheWeek: false,
          image: require('../database/images/อาหารใต้/คั่วกลิ้ง.jpg'),
          Type: 'ผัด',
          Skill: 'ง่าย',
          Time: 20,
        },
        {
          name: 'แกงไตปลา',
          title: 'หรอยแรง!',
          rating: '4.2',
          isTopOfTheWeek: false,
          image: require('../database/images/อาหารใต้/แกงไตปลา.png'),
          Type: 'ต้ม',
          Skill: 'ยาก',
          Time: 30,
        },
      ],
    },
    {
      name: 'อาหารเหนือ',
      image: require('../database/images/อาหารเหนือ/น้ำพริกหนุ่ม.jpg'),
      items: [
        {
          name: 'น้ำพริกหนุ่ม',
          title: 'ทำเองง่ายๆ ลำแต๊ๆเจ๊า',
          rating: '5.0',
          isTopOfTheWeek: true,
          image: require('../database/images/อาหารเหนือ/น้ำพริกหนุ่ม.jpg'),
          Type: 'น้ำพริก',
          Skill: 'ง่าย',
          Time: 30,
        },
        {
          name: 'ข้าวซอยไก่',
          title: 'หอมแกง อร่อยมาก',
          rating: '4.5',
          isTopOfTheWeek: false,
          image: require('../database/images/อาหารเหนือ/ข้าวซอยไก่.jpg'),
          Type: 'บะหมี่',
          Skill: 'ปานกลาง',
          Time: 50,
        },
        {
          name: 'แกงฮังเล',
          title: 'หอมเครื่องแกง รสชาติเข้มข้น',
          rating: '4.2',
          isTopOfTheWeek: false,
          image: require('../database/images/อาหารเหนือ/แกงฮังเล.jpg'),
          Type: 'แกง',
          Skill: 'ยาก',
          Time: 60,
        },
      ],
    },
    {
      name: 'ไข่',
      image: require('../database/images/ไข่/ไข่เจียว.jpg'),
      items: [
        {
          name: 'ไข่เจียวหมูสับ',
          title: 'เหลืองทอง หอมกรุ่น',
          rating: '5.0',
          isTopOfTheWeek: true,
          image: require('../database/images/ไข่/ไข่เจียว.jpg'),
          Type: 'ทอด',
          Skill: 'ง่าย',
          Time: 15,
        },
        {
          name: 'ผัดวุ้นเส้นไข่',
          title: 'อร่อยได้ง่ายๆ',
          rating: '4.5',
          isTopOfTheWeek: false,
          image: require('../database/images/ไข่/ผัดวุ้นเส้น.jpg'),
          Type: 'ผัด',
          Skill: 'ง่าย',
          Time: 15,
        },
        {
          name: 'ไข่พะโล้ + น่องไก่',
          title: 'รสชาติเข้มข้น กลมกล่อม',
          rating: '4.2',
          isTopOfTheWeek: false,
          image: require('../database/images/ไข่/ไข่พะโล้.jpg'),
          Type: 'ต้ม',
          Skill: 'ยาก',
          Time: 60,
        },
      ],
    },
    {
      name: 'ขนม',
      image: require('../database/images/ขนม/ข้าวเหนียวมะม่วง.jpg'),
      items: [
        {
          name: 'ข้าวเหนียวมะม่วง',
          title: 'หอมหวานมันกะทิ',
          rating: '5.0',
          isTopOfTheWeek: true,
          image: require('../database/images/ขนม/ข้าวเหนียวมะม่วง.jpg'),
          Type: 'ผลไม้ขนมหวาน',
          Skill: 'ปานกลาง',
          Time: 50,
        },
        {
          name: 'บัวลอยไข่หวาน',
          title: 'หอมหวานกะทิ อร่อย',
          rating: '4.5',
          isTopOfTheWeek: false,
          image: require('../database/images/ขนม/บัวลอยไข่หวาน.jpg'),
          Type: 'ขนมหวาน',
          Skill: 'ปานกลาง',
          Time: 30,
        },
        {
          name: 'ขนมชั้นใบเตย',
          title: 'หอมกลิ่นใบเตย อร่อยหวานมัน',
          rating: '4.2',
          isTopOfTheWeek: false,
          image: require('../database/images/ขนม/ขนมชั้นใบเตย.jpg'),
          Type: 'ขนมหวาน',
          Skill: 'ยาก',
          Time: 60,
        },
      ],
    },
  ];